# Generated by Django 3.2.6 on 2021-08-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('mate_type', models.CharField(max_length=50)),
                ('activity_area', models.CharField(max_length=50)),
                ('explanation', models.TextField()),
                ('people_number', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='mate/')),
            ],
        ),
    ]
