# Generated by Django 3.2.5 on 2021-08-08 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('mate_type', models.TextField(choices=[('문화생활 메이트', '문화생활 메이트'), ('국내•해외여행 메이트', '국내•해외여행 메이트'), ('캠핑 메이트', '캠핑 메이트'), ('운동 메이트', '운동 메이트'), ('공부 메이트', '공부 메이트')])),
                ('activity_area', models.CharField(max_length=50)),
                ('explanation', models.TextField()),
                ('people_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='mate/')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
